server:
    port: 8001
    servlet:
        context-path: /member

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 1
        url: train_member
        username: root

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
